call pathogen#incubate()
call pathogen#helptags()

nmap <silent> <c-n> :NERDTreeToggle<CR>

:syntax on
:set autochdir
:silent !mkdir -p ~/tmp/vim
:set directory=~/tmp/vim//

" Soft tabs by default
:set tabstop=2
:set shiftwidth=2
:set softtabstop=2
:set expandtab
" Autoindent by default
:set autoindent

au BufRead,BufNewFile *.go set filetype=go
au BufRead,BufNewFile *.pp set filetype=puppet

" Fix vim's ridiculous paste handling when autoindent is on
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
