call pathogen#incubate()
call pathogen#helptags()

nmap <silent> <c-n> :NERDTreeToggle<CR>

:set autochdir
:set directory=~/tmp/vim//

" Soft tabs by default
:set tabstop=2
:set shiftwidth=2
:set softtabstop=2
:set expandtab
" Autoindent by default
:set autoindent
