call pathogen#incubate()
call pathogen#helptags()

nmap <silent> <c-n> :NERDTreeToggle<CR>

:set autochdir
:set directory=~/tmp/vim//

au BufRead,BufNewFile *.rb setfiletype ruby
:autocmd FileType ruby set shiftwidth=2
:autocmd FileType ruby set softtabstop=2
:autocmd FileType ruby set autoindent
:autocmd FileType ruby set expandtab
