# Containers
for index in 1 2 3 5 6 7 10 12 13 17; do
  alias c${index}="ssh c${index}.moov.sh"
done

# Custom prompt
export PS1="\[\033[1;30m\][\[\033[1;34m\]\u\[\033[37m\]@\[\033[31m\]\H\[\033[1;30m\]\[\033[0;32m\]\[\033[1;30m\]] \[\033[1;37m\]\w\[\033[00m\] \n\$ "
